---
- name: Update websites
  hosts: home

  tasks:
    - name: Update Gemini capsule
      shell: cd gemini/ && git pull

    - name: Update HTTP/HTTPS website
      shell: cd /var/www/main && git pull
